// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PluginCommonBase","status":true,"description":"Plugin Analysis Common Base","parameters":{}},
{"name":"TextPicture","status":true,"description":"Displays text as a picture.","parameters":{}},
{"name":"ButtonPicture","status":true,"description":"Makes a picture clickable.","parameters":{}},
{"name":"PictureCallCommon","status":true,"description":"图片的按钮化插件","parameters":{"PictureIdVariable":"3","InvalidSwitchId":"0","FlickDistance":"0","FlickTimeVariable":"0","FlickDegreeVariable":"0"}},
{"name":"DTextPicture","status":true,"description":"动态字符串图片生成插件","parameters":{"frameWindowSkin":"","frameWindowPadding":"18","padCharacter":"0","prefixText":""}},
{"name":"UD_Utils","status":true,"description":"Utils","parameters":{}},
{"name":"UD_SkipTitleScene","status":true,"description":"Skip Title Scene","parameters":{}}
];
